[package]
name = "sht3x"
version = "0.1.0"
authors = ["Mike Walters <mike@flomp.net>"]
keywords = ["embedded-hal"]
categories = ["no-std"]

[dependencies]
byteorder = { version = "1", default-features = false }
embedded-hal = "0.1.1"

[dev-dependencies]
linux-embedded-hal = "0.1.1"
